src/main/java/com/mycompany/webapp/controller/HomeController.java, src/main/java/com/mycompany/webapp/controller/RegisterMyDentistController.java, src/main/java/com/mycompany/webapp/controller/ReservationController.java, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/home/login.jsp, src/main/webapp/WEB-INF/views/home/signIn.jsp, src/main/webapp/WEB-INF/views/registerMyDentist.jsp, src/main/webapp/WEB-INF/views/reservation/registerMyDentist.jsp, src/main/webapp/WEB-INF/views/reservation/reservation.jsp
=> login, logout, reservation Controller 추가 및 jsp a태그 연결

src/main/webapp/WEB-INF/views/myPage/myPagePoint.jsp, src/main/webapp/resources/javascript/myPage/myPoint.js
마이 페이지 내부의 포인트 내역 페이지에서 '전체', '획득', 사용' 탭클릭 시 목록 변화주기.
클릭한 탭에 active 속성 주기.
=> myPage-myPagePoint 리스트 전환, 탭 클릭시 속성 추가

src/main/java/com/mycompany/webapp/controller/MedicalHistoryController.java, src/main/webapp/WEB-INF/views/medicalHistoryPage/medicalHistoryPage.jsp, src/main/webapp/WEB-INF/views/medicalHistoryPage/reviewForm.jsp, src/main/webapp/resources/css/medical-history-page.css
#35  History page UI(진료내역탭) 컨트롤러 연결 및 후기작성폼 구축
=> #35 History page UI 컨트롤러 연결 및 후기작성폼 구축

src/main/webapp/WEB-INF/views/myPage/myPagePoint.jsp, src/main/webapp/resources/javascript/myPage/myPoint.js
=> 포인트 내역 페이지, active 속성 수정.

src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp
=> 진료예약 페이지에서 예약한 셀의 시간값 화면에 표시하기.

src/main/java/com/mycompany/webapp/dao/mybatis/MyDentistsDao.java
=> Temp4 빼먹은 DAO 추가했습니다.

src/main/resources/mybatis/mapper/mydentists.xml
=> mydentists.xml 작성.

src/main/java/com/mycompany/webapp/dao/mybatis/MyDentistsDao.java, src/main/resources/mybatis/mapper/mydentists.xml, src/main/resources/spring/root/component_scan.xml
mydentiststs.xml 작성.
MyDentistsDao.java 수정.(insert, delete 메서드 추가.)
component_scan.xml 수정.(repository 경로 수정.)
=> mydentiststs mapper작성.

src/main/java/com/mycompany/webapp/dao/mybatis/PointDao.java, src/main/resources/mybatis/mapper/points.xml
PointDao.java 수정(@Param("")으로 파라메터 복수개를 매퍼에 전달.).
=> points.xml 작성.

src/main/java/com/mycompany/webapp/dao/mybatis/UserDao.java, src/main/resources/mybatis/mapper/users.xml
UserDao.java 수정.(deleteByUserid메소드 파라미터에 userpassword 추가.).
=> users.xml 수정(insert 메소드에서 칼럼명 나열.).

src/main/resources/mybatis/mapper/comments.xml
comments.xml수정.
mapper-config.xml에서 수정된 alias에 맞게 수정.
CommentDao.java에서 deleteByCommentno()로 수정된 메소드 이름에 맞게 매퍼의 id수정.
=> comments.xml수정.

src/main/java/com/mycompany/webapp/dao/mybatis/PointDao.java, src/main/java/com/mycompany/webapp/service/PointService.java, src/main/resources/mybatis/mapper/point.xml, src/main/resources/mybatis/mapper/user.xml
=> #66 PointService.java 생성.

src/main/java/com/mycompany/webapp/service/BoardService.java
#65 
- 커뮤니티 기능에 쓰일 BoardService 클래스 작성
=> #65 feat: 커뮤니티 기능에 쓰일 BoardService 클래스 작성

src/main/java/com/mycompany/webapp/dao/mybatis/CommentDao.java, src/main/java/com/mycompany/webapp/service/BoardService.java, src/main/java/com/mycompany/webapp/service/CommentService.java
#69 
- 커뮤니티 기능에 쓰일 CommentService 클래스 작성
- 기존 DAO, Service의 메소드명들을 약간씩 수정함
=> #69 feat: 커뮤니티 기능에 쓰일 CommentService 클래스 작성 및 리팩토링

src/main/java/com/mycompany/webapp/dao/mybatis/CommentDao.java, src/main/java/com/mycompany/webapp/dao/mybatis/UserDao.java, src/main/java/com/mycompany/webapp/service/BoardService.java, src/main/java/com/mycompany/webapp/service/CommentService.java, src/main/java/com/mycompany/webapp/service/UserService.java, src/main/resources/mybatis/mapper/user.xml
#72 
- 환자회원객체를 다룰 `UserService` 클래스 작성
- 기존 `UserDao`의 메소드 파라미터를 수정
- 그에 따라 `user.xml` 매퍼도 수정
=> #72 feat: 환자회원객체를 다룰 UserService 클래스 작성 및 리팩토링

src/main/java/com/mycompany/webapp/service/PointService.java
users테이블 update와 points테이블 insert 동시수행시에만 true를 리턴하도록 수정.
=> PointService.java 수정.

src/main/java/com/mycompany/webapp/dao/mybatis/PointDao.java, src/main/java/com/mycompany/webapp/service/PointService.java, src/main/resources/mybatis/mapper/comment.xml, src/main/resources/mybatis/mapper/point.xml
수정한 부분
- PointService, PointDao, Pointxml 수정했습니다.
=> #78 PointService 클래스 추가

src/main/java/com/mycompany/webapp/service/PointService.java, src/main/java/com/mycompany/webapp/service/UserService.java
UserService에 Login Join Method 추가
=> UserService에 Login Join Method 추가

src/main/webapp/WEB-INF/views/common/footer.jsp, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/home/login.jsp
- header.jsp에서 body태그 바로 아래에 class가 'wrapper'인 div태그 추가(footer고정을 위해서
페이지의 내용을 담은 컨테이너로 삼기위함.).
- footer.jsp에서 footer태그 생성 및 기존 태그들의 속성 다수 수정.
- login.jsp에서 일부 id, for, type의 값 수정.
- login.jsp의 하단부에서만, 수정으로 인해 불필요해진 div태그 삭제,section태그와 div태그
닫음.(header.jsp와 연결되는 부분임. 앞으로 모든 jsp파일에 적용해야 됨.)
=> 로그인 페이지를 기준으로 페이지의 길이와 무관하게 페이지 하단에 고정된 footer 작성.

src/main/resources/mybatis/mapper/board.xml
bno -> boardno
btitle -> boardtitle
bcontent -> boardcontent
오타수정.
=> board.xml에서 boards테이블의 컬럼명 잘못 기입한 부분들 수정.

src/main/java/com/mycompany/webapp/controller/MyPageController.java, src/main/java/com/mycompany/webapp/service/UserService.java, src/main/webapp/WEB-INF/views/myPage/myPointList.jsp
데이터 동적으로 주고 받는 기능 구현.
- 로그인한 사용자의 아이디를 session으로부터 얻어서 포인트 잔액과 상세내역(전체/획득/사용)을 출력함.
=> 마이페이지 - 포인트 내역 페이지

src/main/java/com/mycompany/webapp/controller/MyPageController.java, src/main/java/com/mycompany/webapp/service/DentistService.java, src/main/resources/mybatis/mapper/dentist.xml, src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
- 로그인한 사용자의 내치과 목록 출력하는 기능 구현.
- 치과 이름으로 검색하는 기능 구현.
=> [마이페이지] - [내 치과]

src/main/java/com/mycompany/webapp/controller/MyPageController.java, src/main/java/com/mycompany/webapp/dao/mybatis/MyDentistDao.java, src/main/java/com/mycompany/webapp/service/MyDentistService.java, src/main/resources/mybatis/mapper/dentist.xml, src/main/resources/mybatis/mapper/myDentist.xml, src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
<수정 필요 부분>
- dentist.jsp의 모달에 수정이 필요한 부분이 있음.
- 주소로 검색할 수 있도록 드롭박스 추가.
<구현한 부분>
- 로그인한 유저의 '내 치과 목록' 띄우기.
- 내 치과 목록에서 div태그 선택해서 삭제.(모달 수정해야함.)
- 치과 이름으로 검색해서 목록 보여줌.(주소로 검색할 수 있도록 드롭박스 추가해야함.)
- 검색된 치과 목록에서 div태그 클릭해서 '내 치과 목록'에 추가하기. 치과 목록에 추가할 때 mydentists 테이블에
PK가 없으므로 중복추가 방지하는 로직 작성.
=> 예약기능 만들기 전에 내 치과 등록/삭제/조회 기능부터 구현함.

src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp
예시 함수)
function handler(e){
var date = document.getElementById('dateSelect').value=e.target.value;
document.getElementById('timecell').style.visibility="visible";
console.log(date);
var formatDate = date.substr(0,4) + "/" +  date.substr(5,2) + "/" + date.substr(8,2);
console.log(formatDate);
$.ajax({
url:"http://localhost:8080/springframework-mini-project-dentist/availablehour/getHour?date=" + formatDate
})
.done((data) => {
console.log(data.date);
})
}
=> 달력의 날짜 누르면 데이터 넘어오는 ajax 추가

src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/home/main.jsp, src/main/webapp/resources/css/app.css, src/main/webapp/resources/css/header.css
#127 
시안에 작성했던 UI, 유저스토리와 동일하도록 헤더와 사이드바를 바꿨습니다~
(헤더와 사이드바까지만 완료한 상태라 merge만 해주시고 티켓은 close하지 말아주세용)
=> #127 feat: 레이아웃 개선(헤더, 사이드바메뉴)

src/main/java/com/mycompany/webapp/controller/ReservationController.java, src/main/java/com/mycompany/webapp/dao/mybatis/MyDentistDao.java, src/main/java/com/mycompany/webapp/service/MyDentistService.java, src/main/resources/mybatis/mapper/myDentist.xml, src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp, src/main/webapp/WEB-INF/views/reservation/main.jsp
예약을 위한 치과 정보 상세 페이지에서 영업시간 정보를 치과 서버로부터 받아와서 시간형식으로 표시하는 것 구현.
'예약하기'버튼 눌러서 예약 진행 화면으로 넘어가는 링크와 링크 연결 전에 '내 치과' 등록여부 확인해서 등록할 수 있도록 하는
모달 띄우기 필요.
=> 예약을 위한 치과 정보 상세 페이지에서 영업시간 정보를 치과 서버로부터 받아와서 시간형식으로 표시하는 것 구현.

src/main/webapp/WEB-INF/views/myPage/reservationHistoryWithCalendar.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp
=> Jm db schedule

src/main/java/com/mycompany/webapp/controller/ReservationController.java, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/reservation/afterReservationUsingCalendar.jsp, src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingMap.jsp, src/main/webapp/WEB-INF/views/treatment/main.jsp
=> Dh dendomain

src/main/java/com/mycompany/webapp/controller/TreatmentController.java, src/main/java/com/mycompany/webapp/dto/Treatment.java, src/main/webapp/WEB-INF/views/home/login.jsp, src/main/webapp/WEB-INF/views/treatment/details.jsp, src/main/webapp/WEB-INF/views/treatment/imageShow.jsp, src/main/webapp/WEB-INF/views/treatment/main.jsp
#153 
치료 내역 모아보기 목록에서 하나의 치료내역을 클릭 시,<br/>
클릭한 치료번호에 해당하는 정보를 뿌려주는 상세화면으로 넘어가는 기능 구현 완료.
- 치료한 치아🦷 동적으로 그림에 색깔로 표시하기
- 관련 상세내용 차트🩺📋에 표시
- 첨부된 이미지 파일💾(attachment) 동적으로 불러와서 표시
- 이미지파일 하나 누르면 전체보기 화면으로 넘어가는 기능까지 구현
- 치료비💸는 3자리마다 콤마 찍히게끔 표시
=> #153 feat: 치료내역 모아보기 목록에서 하나 클릭시 넘어가는 기능 구현

src/main/java/com/mycompany/webapp/controller/MyPageController.java, src/main/java/com/mycompany/webapp/controller/ReservationController.java, src/main/webapp/WEB-INF/views/myPage/main.jsp, src/main/webapp/WEB-INF/views/myPage/myInformation.jsp, src/main/webapp/WEB-INF/views/myPage/signOut.jsp, src/main/webapp/WEB-INF/views/reservation/main.jsp
회원탈퇴 기능 추가했습니다.
내 설정 화면에 정보 띄우는 기능 추가했습니다.
진료 예약하기에 기본으로 내 치과 뜨게 하는 기능 추가했습니다.
=> #155 dh 회원탈퇴, 내 설정 화면, 진료예약 화면 기능 추가

src/main/java/com/mycompany/webapp/controller/BoardController.java, src/main/java/com/mycompany/webapp/controller/HomeController.java, src/main/java/com/mycompany/webapp/controller/MyPageController.java, src/main/java/com/mycompany/webapp/service/BoardService.java, src/main/java/com/mycompany/webapp/service/CommentService.java, src/main/webapp/WEB-INF/views/board/boardDetail.jsp, src/main/webapp/WEB-INF/views/home/login.jsp, src/main/webapp/WEB-INF/views/myPage/reservationHistoryWithCalendar.jsp
board랑 comment에 없는 회원은 알 수 없음 처리 추가
글 작성과 댓글 작성시 로그인 페이지로 포워드하고 오류메세지 띄우기 기능 추가
달력에 예약기록 띄우는 기능 추가
=> dh formerror 및 달력 예약기록 추가

src/main/webapp/WEB-INF/views/myPage/myReservationList.jsp
=> Sukhee myreservation

src/main/java/com/mycompany/webapp/controller/ReservationController.java, src/main/webapp/WEB-INF/views/board/boardDetail.jsp, src/main/webapp/WEB-INF/views/board/boardList.jsp, src/main/webapp/WEB-INF/views/board/boardWriteForm.jsp, src/main/webapp/WEB-INF/views/board/searchBoardList.jsp, src/main/webapp/WEB-INF/views/myPage/easteregg.jsp, src/main/webapp/WEB-INF/views/myPage/myDentist.jsp, src/main/webapp/WEB-INF/views/reservation/afterReservationUsingCalendar.jsp, src/main/webapp/WEB-INF/views/reservation/main.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingMap.jsp
예약 페이지 자기 포인트 출력 및 10000차감
게시판 살짝 수정
마커 클릭시 페이지 이동 기능 삭제
myDentist 검색창 수정
=> Jm discountcheck

src/main/webapp/WEB-INF/views/common/loading.jsp, src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
#182
- loading.jsp 코드 수정
- myPage/myDentist.jsp에서 loading.jsp가 include된 위치 수정(head태그 안에서 body태그 안으로)
@lee0507
loading.jsp가 컴포넌트인거 같아 보이는데 html태그가 다 작성된 바람에 페이지 타이틀(크롬탭에서 보이는 그 타이틀)이 insert title here로 뜨길래 html태그나 body태그 등 지웠어영~ 그리고 loading.jsp 위치도 각 페이지마다 head 태그 안에 들어가잇는거같은데 제가 이 PR에서 한것처럼 나머지 페이지들도 body 태그 안으로 넣어주심 ㄳ하겟습니다
=> #182 debug: loading.jsp 내용수정 및 위치 일부 수정(나머지는 동현쓰에게 토스)

src/main/java/com/mycompany/webapp/controller/MyPageController.java, src/main/webapp/WEB-INF/views/common/loading.jsp, src/main/webapp/WEB-INF/views/myPage/myDentist.jsp, src/main/webapp/WEB-INF/views/myPage/myReservationList.jsp, src/main/webapp/resources/css/app.css, src/main/webapp/resources/css/myPage/myReservationList.css
#127 
- 몰라 걍 짱 힘드렁ㅆ다.....
- 대대적인 리팩토링도 진행햇습니다
이후에 더 UI 건드는 작업 있을수도 있으니까 티켓은 계속 열여둬주세여..
=> #127 feat: 레이아웃 개선(myPage 예약현황 화면)

src/main/webapp/WEB-INF/views/reservation/main.jsp
reservation/main 페이지네이션용 버튼 UI수정. '내 치과' 페이지와 같은 모양새로 만듦.
게시판의 페이지네이션용 버튼도 UI 통일할 필요 있다고 생각됨.
=> [sukhee-ui] reservation/main 페이지네이션용 버튼 UI수정.

src/main/java/com/mycompany/webapp/controller/ReservationController.java, src/main/webapp/WEB-INF/views/board/boardDetail.jsp, src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp, src/main/webapp/WEB-INF/web.xml
치과 정보 상세 페이지 상단에 치과 대표 이미지(인테리어 전경) 추가하기 구현. 이미지를 억지로 화면 너비에 맞췄더니 화질이
떨어짐. 수정필요.
=> [sukhee-dentist-image] 치과 정보 상세 페이지에서 치과서버로부터 전달받은 대표 이미지 표시하기 구현.

src/main/webapp/WEB-INF/views/myPage/myDentist.jsp, src/main/webapp/WEB-INF/views/myPage/myReservationList.jsp
#186 
예약현황 화면에서 예약취소 선택 시 "정말 취소하시겠습니까?" 물어보는 confirm 모달기능 구현하기
&& (Dentist서버단) 디폴트로 취소사유는 "본인 취소"로 DB에 들어가게 하기([Dentist단 프로젝트에서 한 PR](https://github.com/SukheeChoi/springframework-mini-project-dentist/issues/45) 참고 부탁드려용)
=> #186 feat: 예약현황 화면에서 예약취소 선택 시 confirm 모달 구현

src/main/webapp/WEB-INF/views/myPage/reservationHistoryWithCalendar.jsp, src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingMap.jsp
reservationusingmap 치과 이름 글씨 작게
시간 선택 디폴트 화면에 
전화번호 눌렀을때 전화가 가능
캘린더 밑에서 상세보기가 올라오는 애니메이션을 적용
=> Jm UI modify

src/main/java/com/mycompany/webapp/controller/TreatmentController.java, src/main/webapp/WEB-INF/views/treatment/details.jsp, src/main/webapp/WEB-INF/views/treatment/main.jsp
=> Dh dentist detail

src/main/webapp/WEB-INF/views/home/signup.jsp, src/main/webapp/WEB-INF/views/myPage/reservationHistoryWithCalendar.jsp
- 회원가입 창에 이메일 양식 폼 추가.
- DB연동 확인완료.
=> Sukhee emailform

src/main/webapp/WEB-INF/views/myPage/myDentist.jsp, src/main/webapp/resources/css/reservation/reservationUsingMap.css
#201 
myPage/myDentist.jsp 페이지에서 쓰인 denno 관련 변수 전부 dendomain으로 변경했습니당
=> #201 feat: myDentist.jsp페이지 denno->dendomain으로 변경

src/main/java/com/mycompany/webapp/controller/MyPageController.java, src/main/java/com/mycompany/webapp/dao/mybatis/DentistDao.java, src/main/java/com/mycompany/webapp/dao/mybatis/MyDentistDao.java, src/main/java/com/mycompany/webapp/service/DentistService.java, src/main/java/com/mycompany/webapp/service/MyDentistService.java, src/main/resources/mybatis/mapper/dentist.xml, src/main/resources/mybatis/mapper/myDentist.xml, src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
마이페이지 - 내 치과에서 denno 사용하는 로직 전부 dendomain 사용하도록 수정.
=> Transform to dendomain my dentist

src/main/java/com/mycompany/webapp/controller/ReservationController.java, src/main/webapp/WEB-INF/views/reservation/main.jsp, src/main/webapp/WEB-INF/views/reservation/reservationUsingMap.jsp
예약하기에서 denno사용하는 로직 dendomain사용하는 로직으로 수정.
=> 예약하기에서 denno사용하는 로직 dendomain사용하는 로직으로 수정.

src/main/webapp/WEB-INF/views/myPage/myDentist.jsp, src/main/webapp/resources/css/common/empty-block.css, src/main/webapp/resources/css/common/list-item.css, src/main/webapp/resources/css/common/search-bar.css, src/main/webapp/resources/css/myPage/myDentist.css
#211 
- 검색바 css를 common/ 밑에 두고 쓸 수 있도록 컴포넌트화했음
- 기존 common/ 밑의 컴포넌트들에 설명주석 달기 및 스타일 수정했음(width를 넘기면 텍스트 끝에 ... 처리하고 자르기 등)
=> #211 feat && refactor: 검색바 UI컴포넌트 추가 및 기존 컴포넌트 수정

src/main/webapp/WEB-INF/views/treatment/reviewForm.jsp
#216 
치료내역 상세화면>리뷰작성화면에서 치료내역의 요약정보가 뜨지 않는 현상 해결했습니다.
원인: dendomain 값 8082로 하드코딩했던 걸 수정하지 않아서 생겼던 문제...
=> #216 debug: 치료내역상세 > 리뷰작성화면에서 치료내역의 요약정보가 뜨지 않던 현상 해결
